import 'package:flutter/material.dart';

void main() {
  runApp(const AbsensiApp());
  }

  class AbsensiApp extends StatelessWidget {
    const AbsensiApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  title: 'Absensi Karyawan',
                        theme: ThemeData(
                                primarySwatch: Colors.blue,
                                      ),
                                            home: const AbsensiHomePage(),
                                                );
                                                  }
                                                  }

                                                  class AbsensiHomePage extends StatefulWidget {
                                                    const AbsensiHomePage({super.key});

                                                      @override
                                                        State<AbsensiHomePage> createState() => _AbsensiHomePageState();
                                                        }

                                                        class _AbsensiHomePageState extends State<AbsensiHomePage> {
                                                          List<String> daftarAbsensi = [];

                                                            void _absenKaryawan(String nama) {
                                                                setState(() {
                                                                      daftarAbsensi.add("$nama hadir pada ${DateTime.now()}");
                                                                          });
                                                                            }

                                                                              final TextEditingController _controller = TextEditingController();

                                                                                @override
                                                                                  Widget build(BuildContext context) {
                                                                                      return Scaffold(
                                                                                            appBar: AppBar(
                                                                                                    title: const Text("Absensi Karyawan"),
                                                                                                          ),
                                                                                                                body: Padding(
                                                                                                                        padding: const EdgeInsets.all(16.0),
                                                                                                                                child: Column(
                                                                                                                                          children: [
                                                                                                                                                      TextField(
                                                                                                                                                                    controller: _controller,
                                                                                                                                                                                  decoration: const InputDecoration(
                                                                                                                                                                                                  labelText: "Nama Karyawan",
                                                                                                                                                                                                                  border: OutlineInputBorder(),
                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                        const SizedBox(height: 10),
                                                                                                                                                                                                                                                                    ElevatedButton(
                                                                                                                                                                                                                                                                                  onPressed: () {
                                                                                                                                                                                                                                                                                                  if (_controller.text.isNotEmpty) {
                                                                                                                                                                                                                                                                                                                    _absenKaryawan(_controller.text);
                                                                                                                                                                                                                                                                                                                                      _controller.clear();
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                  child: const Text("Absen"),
                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                      Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                    child: ListView.builder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    itemCount: daftarAbsensi.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                leading: const Icon(Icons.person),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: Text(daftarAbsensi[index]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }